import Link from "next/link";
import { SiteShell, PageHero, Arrow, ContactBand } from "../site-shell";

const programs=[
 {type:"Management",title:"Manager avec impact",desc:"Les fondamentaux pour mobiliser, responsabiliser et faire progresser son équipe.",meta:"2 à 3 jours · Présentiel ou hybride",topics:["Posture","Délégation","Feedback"]},
 {type:"Leadership",title:"Réussir sa prise de poste",desc:"Un parcours accélérateur pour clarifier son mandat et réussir ses 100 premiers jours.",meta:"6 semaines · Parcours blended",topics:["Diagnostic","Influence","Plan 100 jours"]},
 {type:"Performance",title:"Culture du feedback",desc:"Faire du feedback un réflexe simple, constructif et utile à la performance.",meta:"1 jour + suivi · En équipe",topics:["Courage","Écoute","Conversations"]},
 {type:"Carrière",title:"Future-ready talents",desc:"Préparer les jeunes potentiels aux attentes et aux codes du monde professionnel.",meta:"4 ateliers · Cohorte",topics:["Soft skills","Projet","Employabilité"]},
];
export default function Programmes(){return <SiteShell active="programmes"><main><PageHero eyebrow="Nos programmes" title={<>Des formats conçus pour<br/><em>faire pratiquer.</em></>} intro="Des programmes structurés, adaptables à votre contexte et animés avec une pédagogie active."/><section className="section soft-section"><div className="container program-grid">{programs.map((p,i)=><article className="program-card" key={p.title}><div className="program-top"><span>{p.type}</span><b>0{i+1}</b></div><h2>{p.title}</h2><p>{p.desc}</p><div className="chips">{p.topics.map(t=><span key={t}>{t}</span>)}</div><div className="program-bottom"><small>{p.meta}</small><Link href="/contact" aria-label={`En savoir plus sur ${p.title}`}><Arrow/></Link></div></article>)}</div></section><section className="section container process"><div><p className="eyebrow">Notre pédagogie</p><h2>On retient ce que<br/>l’on met en pratique.</h2></div><ol><li><span>01</span><div><b>Avant</b><p>Comprendre le contexte et fixer les résultats attendus.</p></div></li><li><span>02</span><div><b>Pendant</b><p>Expérimenter, échanger et travailler sur des cas réels.</p></div></li><li><span>03</span><div><b>Après</b><p>Ancrer les acquis par des défis, du suivi et du feedback.</p></div></li></ol></section><ContactBand/></main></SiteShell>}
