import Link from "next/link";
import { SiteShell, PageHero, Arrow, ContactBand } from "../site-shell";

const solutions = [
 {id:"entreprises",num:"01",tag:"Entreprises",title:"Faire évoluer l’organisation par ses talents.",text:"Nous concevons des parcours sur mesure reliés à vos enjeux : culture managériale, engagement, coopération et performance commerciale.",items:["Diagnostic des besoins","Académies internes","Ateliers d’intelligence collective","Accompagnement du changement"]},
 {id:"managers",num:"02",tag:"Managers",title:"Passer d’expert à leader mobilisateur.",text:"Des expériences pratiques pour mieux se connaître, communiquer avec impact et créer les conditions de la performance collective.",items:["Prise de poste","Leadership situationnel","Feedback & conversations difficiles","Pilotage de la performance"]},
 {id:"talents",num:"03",tag:"Jeunes talents",title:"Donner une longueur d’avance aux potentiels.",text:"Un accompagnement pour développer les compétences humaines et professionnelles indispensables à une entrée réussie dans le monde du travail.",items:["Confiance & posture","Communication professionnelle","Gestion de projet","Employabilité & carrière"]},
];
export default function Solutions(){return <SiteShell active="solutions"><main><PageHero eyebrow="Nos solutions" title={<>Des interventions qui répondent<br/><em>à vos vrais enjeux.</em></>} intro="Du parcours d’entreprise à l’accompagnement individuel, nous construisons le format adapté à votre ambition."/><section className="section container solution-list">{solutions.map((s,i)=><article id={s.id} className="solution-row" key={s.id}><div className="solution-num">{s.num}</div><div><p className="eyebrow">{s.tag}</p><h2>{s.title}</h2><p>{s.text}</p><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul><Link className="text-link" href="/contact">Construire une solution <Arrow/></Link></div><div className={`shape shape-${i+1}`}><span>{s.num}</span></div></article>)}</section><ContactBand/></main></SiteShell>}
